config/routes.rb
Rails.application.routes.draw do
  resources :shots
  devise_for :users, controller: { registrations: 'registrations'}

  root 'shots#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shot.rb
class Shot < ApplicationRecord

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shots, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :set_shot, only: %i[ show edit update destroy ]

  # GET /shots or /shots.json
  def index
    @shots = Shot.all
  end

  # GET /shots/1 or /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = current_user.shots.build
  end

  # GET /shots/1/edit
  def edit
  end

  # POST /shots or /shots.json
  def create
    @shot = current_user.shots.new(shot_params)

    respond_to do |format|
      if @shot.save
        format.html { redirect_to shot_url(@shot), notice: "Shot was successfully created." }
        format.json { render :show, status: :created, location: @shot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shots/1 or /shots/1.json
  def update
    respond_to do |format|
      if @shot.update(shot_params)
        format.html { redirect_to shot_url(@shot), notice: "Shot was successfully updated." }
        format.json { render :show, status: :ok, location: @shot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shots/1 or /shots/1.json
  def destroy
    @shot.destroy

    respond_to do |format|
      format.html { redirect_to shots_url, notice: "Shot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shot
      @shot = Shot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shot_params
      params.require(:shot).permit(:title, :description,:user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dribby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/shots/_form.html.erb
<%= simple_form_for(@shot) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shots/_shot.html.erb
<div id="<%= dom_id shot %>">
  <p>
    <strong>Title:</strong>
    <%= shot.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= shot.description %>
  </p>

  <p>

  <i> By <%= current_user.email %> </i>

  <p>
  <br>

</div>

app/views/shots/edit.html.erb
<h1>Editing shot</h1>

<%= render "form", shot: @shot %>

<br>

<div>
  <%= link_to "Show this shot", @shot %> |
  <%= link_to "Back to shots", shots_path %>
</div>

app/views/shots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shots</h1>

<div id="shots">

  <% @shots.each do |shot| %>
    <%= render shot %>
    <p>
      <%= link_to "Show this shot", shot %>
    </p>
  <% end %>
</div>

<%= link_to "New shot", new_shot_path %>

app/views/shots/new.html.erb
<h1>New shot</h1>

  <% if @shot.errors.any? %>

    
   <% @shot.errors.full_messages.each do |error| %></h1>
     <h2><%= error %></h2>
   <% end %>
  <% end %>

<%= render "form", shot: @shot %>

<br>

<div>
  <%= link_to "Back to shots", shots_path %>
</div>

app/views/shots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shot %>

<div>
  <%= link_to "Edit this shot", edit_shot_path(@shot) %> |
  <%= link_to "Back to shots", shots_path %>

  <%= button_to "Destroy this shot", @shot, method: :delete %>
</div>